using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Reports
{
    class FakeData
    {
        public int Semestr { get; set; }
        public int Course { get; set; }
        public string EduForm { get; set; }
        public string FlowAndGroup { get; set; }
        public List<string> Teachers { get; set; }

        public static List<FakeData> GetFakeData()
        {
            return new List<FakeData>() { 
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad","Tom","Nazar"})},
                new FakeData(){Semestr =1, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Igor","Nazar"})},
                new FakeData(){Semestr =2, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Kate"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Sasha","Igor"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Alex"})},
                new FakeData(){Semestr =1, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Tanya","Maya"})},
                new FakeData(){Semestr =1, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Bob"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =1, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad","Igor"})},
                new FakeData(){Semestr =2, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Pasha"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Nazar"})},
                new FakeData(){Semestr =2, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =2, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Jack","Mike","Igor","Nazar"})},
                new FakeData(){Semestr =1, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Viktor","Pasha","Igor","Nazar"})},
                new FakeData(){Semestr =2, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Jack"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =2, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Rob","Vlad","Tom","Nazar"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Jack","Igor","Nazar"})},
                new FakeData(){Semestr =2, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Miroslav","Vlad","Viktor"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad","Tom","Nazar"})},
                new FakeData(){Semestr =1, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Igor","Nazar"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Kate"})},
                new FakeData(){Semestr =2, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Sasha","Igor"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Alex"})},
                new FakeData(){Semestr =1, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Tanya","Maya"})},
                new FakeData(){Semestr =1, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Bob"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =2, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad","Igor"})},
                new FakeData(){Semestr =2, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Pasha"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Nazar"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =1, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Jack","Mike","Igor","Nazar"})},
                new FakeData(){Semestr =1, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Viktor","Pasha","Igor","Nazar"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =1, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Jack"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Rob","Vlad","Tom","Nazar"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Jack","Igor","Nazar"})},
                new FakeData(){Semestr =2, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Miroslav","Vlad","Viktor"})},
                new FakeData(){Semestr =2, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad","Tom","Nazar"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Igor","Nazar"})},
                new FakeData(){Semestr =2, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Kate"})},
                new FakeData(){Semestr =1, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Sasha","Igor"})},
                new FakeData(){Semestr =2, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Alex"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =1, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Tanya","Maya"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Bob"})},
                new FakeData(){Semestr =2, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad","Igor"})},
                new FakeData(){Semestr =1, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Pasha"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Nazar"})},
                new FakeData(){Semestr =1, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =1, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Jack","Mike","Igor","Nazar"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Viktor","Pasha","Igor","Nazar"})},
                new FakeData(){Semestr =1, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Jack"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =2, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Rob","Vlad","Tom","Nazar"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Jack","Igor","Nazar"})},
                new FakeData(){Semestr =1, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Miroslav","Vlad","Viktor"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad","Tom","Nazar"})},
                new FakeData(){Semestr =2, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Igor","Nazar"})},
                new FakeData(){Semestr =2, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Kate"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Sasha","Igor"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Alex"})},
                new FakeData(){Semestr =2, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Tanya","Maya"})},
                new FakeData(){Semestr =1, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Bob"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =1, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad","Igor"})},
                new FakeData(){Semestr =1, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Pasha"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Nazar"})},
                new FakeData(){Semestr =2, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =1, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Jack","Mike","Igor","Nazar"})},
                new FakeData(){Semestr =2, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Viktor","Pasha","Igor","Nazar"})},
                new FakeData(){Semestr =1, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Jack"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =2, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Rob","Vlad","Tom","Nazar"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Jack","Igor","Nazar"})},
                new FakeData(){Semestr =1, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Miroslav","Vlad","Viktor"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad","Tom","Nazar"})},
                new FakeData(){Semestr =1, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Igor","Nazar"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Kate"})},
                new FakeData(){Semestr =1, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Sasha","Igor"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Alex"})},
                new FakeData(){Semestr =1, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Tanya","Maya"})},
                new FakeData(){Semestr =2, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Bob"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =1, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad","Igor"})},
                new FakeData(){Semestr =2, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Pasha"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Nazar"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =1, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Jack","Mike","Igor","Nazar"})},
                new FakeData(){Semestr =1, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Viktor","Pasha","Igor","Nazar"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =1, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Jack"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Rob","Vlad","Tom","Nazar"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Jack","Igor","Nazar"})},
                new FakeData(){Semestr =1, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Miroslav","Vlad","Viktor"})},
                new FakeData(){Semestr =2, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad","Tom","Nazar"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Igor","Nazar"})},
                new FakeData(){Semestr =1, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Kate"})},
                new FakeData(){Semestr =2, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Sasha","Igor"})},
                new FakeData(){Semestr =2, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Alex"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =1, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Tanya","Maya"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Bob"})},
                new FakeData(){Semestr =1, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad","Igor"})},
                new FakeData(){Semestr =2, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Pasha"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Nazar"})},
                new FakeData(){Semestr =1, Course=4, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =2, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Jack","Mike","Igor","Nazar"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Viktor","Pasha","Igor","Nazar"})},
                new FakeData(){Semestr =1, Course=2, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Jack"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Vlad"})},
                new FakeData(){Semestr =1, Course=3, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Rob","Vlad","Tom","Nazar"})},
                new FakeData(){Semestr =2, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max","Jack","Igor","Nazar"})},
                new FakeData(){Semestr =1, Course=1, EduForm="day", FlowAndGroup="IS-12", Teachers=new List<string>(new string[]{"Max"})}
            };
        }

    }
}
